/*ORDERS ARE STORED IN SEPARATE TABLES(Orders and OrdersArchive), COMBINE ALL ORDERS INTO ONE REPORT WITHOUT DUPLICTES*/

--START BY EXPLORING BOTH TABLES, REMEMBER HIGHLIGHTING OVER A PORTION OF CODE EXECUTES ONLY THAT PORTION OF CODE.

SELECT
*
FROM Sales.Orders


SELECT 
*
FROM SALES.OrdersArchive


/*AND NOW WE ADD UNION TO COMBINE THE TABLES INTO ONE*/
SELECT
*
FROM Sales.Orders

UNION -- RESULTS IN A SINGLE RESULT WITH A COMBINATION OF DATA FROM Sales.Orders TABLE AND Sales.OrdersArchive TABLE

SELECT 
*
FROM SALES.OrdersArchive

/*BUT USING UNION RESULTS IN A DIRTY RESLUT WITHOUT MUCH OF YOUR CONTROL, A BETTER WAY:*/
/*RIGHT CLICK TABLE IN EXPLORER AND SELECT TOP 1000 ROWS - THIS WILL RESULT IN A SIMPLE SELECT STRATEMENT WITH ALL COLUMN NAMES, THAT WAY YOU DON'T HAVE TO WRITE THEM OUT*/
/*NOW COPY AND PASTE THE COLUMN NAMES INTO BOTH SELECT STATEMENTS WHERE THE STAR IS*/
/*EXECUTE TO RESULT IN A BETTER RESULT WE AR E SURE IS 100% MATCHING THAT YOU CAN CHANGE AROUND LIKE SWITCHING THE COLUMNS AROUND OR RENAMING THEM*/
/*INCLUDE ADDITIONAL COLUMN TO INDICATE THE SOURCE OF EACH ROW*/
SELECT --REMEMBER ORDER OF COLUMN NAMES IN FIRST STATEMENT INFLUENCES ORDER OF COLUMNS IN RESULT
       'Orders' As SourceTable, --ADDS STATIC COLUMNS TO QUERY IN ORDER TO SEE THE SOURCE OF THE TABLE 
	   [OrderID]
      ,[ProductID]
      ,[CustomerID]
      ,[SalesPersonID]
      ,[OrderDate]
      ,[ShipDate]
      ,[OrderStatus]
      ,[ShipAddress]
      ,[BillAddress]
      ,[Quantity]
      ,[Sales]
      ,[CreationTime]
FROM Sales.Orders

UNION -- RESULTS IN A SINGLE RESULT WITH A COMBINATION OF DATA FROM Sales.Orders TABLE AND Sales.OrdersArchive TABLE

SELECT 
	   'OrdersArchive' As SourceTable,
	   [OrderID]
      ,[ProductID]
      ,[CustomerID]
      ,[SalesPersonID]
      ,[OrderDate]
      ,[ShipDate]
      ,[OrderStatus]
      ,[ShipAddress]
      ,[BillAddress]
      ,[Quantity]
      ,[Sales]
      ,[CreationTime]
FROM SALES.OrdersArchive
ORDER BY OrderID --THIS SPECIFIES THE SOURCE TABLE OF THE SAME ORDER IDs 

/**/
