--FIND EMPLOYEES WHO ARE NOT EMPLOYEES AT THE SAME TIME

SELECT -- OUR FOCUS IS ON EMPLOYEES THEREFORE IT MAKES SENSE TO START OUR FOCUS THERE
FirstName,
LastName
FROM Sales.Employees

EXCEPT     --ORDER OF QUERIES AFFECT THE RESULT

SELECT
FirstName,
LastName
FROM Sales.Customers 