/*FIND EMPLOYEES WHO ARE ALSO CUSTOMERS*/

SELECT -- OUR FOCUS IS ON EMPLOYEES THEREFORE IT MAKES SENSE TO START OUR FOCUS THERE
FirstName,
LastName
FROM Sales.Employees

INTERSECT     --ORDER OF QUERIES AFFECT THE RESULT

SELECT
FirstName,
LastName
FROM Sales.Customers 