/*USE SET OPERATOR 'EXCEPT' TO IDENTIFY NEW DATA BY COMPARING RECORDS THIS WILL CREATE A NEW RECORD TO GO INTO DATA WAREHOUSE*/
/*USE EXEPT TO ALSO CHECK FOR DATA COMPLETENESS*/

--MOVING A TABLE FROM DATABSE A TO DATABASE B
--CHECK WHETHER ALL RECORDS ACTUALLY MOVED --DATA COMPLETENESS

--THE RESULT IF DATA IS COMPLETE SHOULD BE EMPTY

--NIOW CHECK ALL RECORDS IN DATABSE B TABLE MOVED TO DATABASE A TABLE--BASICALLY REVERSE THE OPERATION

--THE RESULT SHOULD ALSO BE EMPTY TO SHOW BOTH TABLES ARE IDENTICAL